///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest9
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("5be2b457-704e-42ae-a959-3b7116f68f9a", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest9Repository repository.
        /// </summary>
        public static MyTest9Repository repo = MyTest9Repository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TestDatabase' at 48;12.", repo.ApplicationUnderTest.TestDatabaseInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.TestDatabase.Click("48;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.FirstName' at 102;9.", repo.ApplicationUnderTest.RxTabStandard.FirstNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.RxTabStandard.FirstName.Click("102;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'er' with focus on 'ApplicationUnderTest.TestDatabase'.", repo.ApplicationUnderTest.TestDatabaseInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.TestDatabase.PressKeys("er");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.LastName' at 111;4.", repo.ApplicationUnderTest.RxTabStandard.LastNameInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.RxTabStandard.LastName.Click("111;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'tt' with focus on 'ApplicationUnderTest.RxTabStandard.LastName'.", repo.ApplicationUnderTest.RxTabStandard.LastNameInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.RxTabStandard.LastName.PressKeys("tt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabStandard.BtnAddPerson' at 48;15.", repo.ApplicationUnderTest.RxTabStandard.BtnAddPersonInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.RxTabStandard.BtnAddPerson.Click("48;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1') on item 'ApplicationUnderTest.RxTabStandard.LblNumberOfPersonsNumber'.", repo.ApplicationUnderTest.RxTabStandard.LblNumberOfPersonsNumberInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RxTabStandard.LblNumberOfPersonsNumberInfo, "Text", "1");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
